# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'design_2lab.ui'
##
## Created by: Qt User Interface Compiler version 6.9.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QDoubleSpinBox, QFrame, QLabel,
    QMainWindow, QPushButton, QRadioButton, QSizePolicy,
    QSlider, QSpinBox, QStatusBar, QTabWidget,
    QWidget)

class Ui_Imchanger(object):
    def setupUi(self, Imchanger):
        if not Imchanger.objectName():
            Imchanger.setObjectName(u"Imchanger")
        Imchanger.resize(1256, 936)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Imchanger.sizePolicy().hasHeightForWidth())
        Imchanger.setSizePolicy(sizePolicy)
        self.actionload_file = QAction(Imchanger)
        self.actionload_file.setObjectName(u"actionload_file")
        icon = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.DocumentSave))
        self.actionload_file.setIcon(icon)
        self.actionload_file.setMenuRole(QAction.MenuRole.NoRole)
        self.centralwidget = QWidget(Imchanger)
        self.centralwidget.setObjectName(u"centralwidget")
        self.filename_label = QLabel(self.centralwidget)
        self.filename_label.setObjectName(u"filename_label")
        self.filename_label.setGeometry(QRect(190, 10, 331, 31))
        self.filename_label.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.load_button = QPushButton(self.centralwidget)
        self.load_button.setObjectName(u"load_button")
        self.load_button.setGeometry(QRect(20, 10, 161, 26))
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(10, 40, 1251, 871))
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.main_tab = QWidget()
        self.main_tab.setObjectName(u"main_tab")
        self.origin_img_frame = QFrame(self.main_tab)
        self.origin_img_frame.setObjectName(u"origin_img_frame")
        self.origin_img_frame.setGeometry(QRect(210, 10, 400, 400))
        self.origin_img_frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.origin_img_frame.setFrameShadow(QFrame.Shadow.Raised)
        self.chroma_img_frame = QFrame(self.main_tab)
        self.chroma_img_frame.setObjectName(u"chroma_img_frame")
        self.chroma_img_frame.setGeometry(QRect(210, 420, 400, 400))
        self.chroma_img_frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.chroma_img_frame.setFrameShadow(QFrame.Shadow.Raised)
        self.smooth_img_frame = QFrame(self.main_tab)
        self.smooth_img_frame.setObjectName(u"smooth_img_frame")
        self.smooth_img_frame.setGeometry(QRect(630, 10, 400, 400))
        self.smooth_img_frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.smooth_img_frame.setFrameShadow(QFrame.Shadow.Raised)
        self.clarity_img_frame = QFrame(self.main_tab)
        self.clarity_img_frame.setObjectName(u"clarity_img_frame")
        self.clarity_img_frame.setGeometry(QRect(630, 420, 400, 400))
        self.clarity_img_frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.clarity_img_frame.setFrameShadow(QFrame.Shadow.Raised)
        self.label1 = QLabel(self.main_tab)
        self.label1.setObjectName(u"label1")
        self.label1.setGeometry(QRect(50, 190, 121, 51))
        font = QFont()
        font.setPointSize(16)
        self.label1.setFont(font)
        self.label1.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label2 = QLabel(self.main_tab)
        self.label2.setObjectName(u"label2")
        self.label2.setGeometry(QRect(70, 530, 121, 51))
        self.label2.setFont(font)
        self.label2.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label3 = QLabel(self.main_tab)
        self.label3.setObjectName(u"label3")
        self.label3.setGeometry(QRect(1080, 190, 104, 26))
        self.label3.setFont(font)
        self.label3.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label4 = QLabel(self.main_tab)
        self.label4.setObjectName(u"label4")
        self.label4.setGeometry(QRect(1030, 540, 121, 51))
        self.label4.setFont(font)
        self.label4.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.tabWidget.addTab(self.main_tab, "")
        self.chroma_tab = QWidget()
        self.chroma_tab.setObjectName(u"chroma_tab")
        self.chroma_frame = QFrame(self.chroma_tab)
        self.chroma_frame.setObjectName(u"chroma_frame")
        self.chroma_frame.setGeometry(QRect(80, 70, 600, 600))
        self.chroma_frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.chroma_frame.setFrameShadow(QFrame.Shadow.Raised)
        self.label = QLabel(self.chroma_tab)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(730, 150, 211, 20))
        self.label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.log_button = QPushButton(self.chroma_tab)
        self.log_button.setObjectName(u"log_button")
        self.log_button.setGeometry(QRect(730, 120, 161, 26))
        self.power_button = QPushButton(self.chroma_tab)
        self.power_button.setObjectName(u"power_button")
        self.power_button.setGeometry(QRect(730, 150, 161, 26))
        self.binary_button = QPushButton(self.chroma_tab)
        self.binary_button.setObjectName(u"binary_button")
        self.binary_button.setGeometry(QRect(730, 180, 161, 26))
        self.range_button = QPushButton(self.chroma_tab)
        self.range_button.setObjectName(u"range_button")
        self.range_button.setGeometry(QRect(720, 320, 161, 26))
        self.gamma_label = QLabel(self.chroma_tab)
        self.gamma_label.setObjectName(u"gamma_label")
        self.gamma_label.setGeometry(QRect(900, 150, 71, 20))
        self.gamma_slider = QSlider(self.chroma_tab)
        self.gamma_slider.setObjectName(u"gamma_slider")
        self.gamma_slider.setGeometry(QRect(970, 150, 161, 22))
        self.gamma_slider.setMinimum(1)
        self.gamma_slider.setMaximum(50)
        self.gamma_slider.setValue(10)
        self.gamma_slider.setOrientation(Qt.Orientation.Horizontal)
        self.gamma_spin = QDoubleSpinBox(self.chroma_tab)
        self.gamma_spin.setObjectName(u"gamma_spin")
        self.gamma_spin.setGeometry(QRect(1140, 150, 62, 22))
        self.gamma_spin.setMinimum(0.100000000000000)
        self.gamma_spin.setMaximum(5.000000000000000)
        self.gamma_spin.setValue(1.000000000000000)
        self.threshold_label = QLabel(self.chroma_tab)
        self.threshold_label.setObjectName(u"threshold_label")
        self.threshold_label.setGeometry(QRect(900, 190, 71, 20))
        self.threshold_slider = QSlider(self.chroma_tab)
        self.threshold_slider.setObjectName(u"threshold_slider")
        self.threshold_slider.setGeometry(QRect(980, 190, 161, 22))
        self.threshold_slider.setMinimum(0)
        self.threshold_slider.setMaximum(255)
        self.threshold_slider.setValue(128)
        self.threshold_slider.setOrientation(Qt.Orientation.Horizontal)
        self.threshold_spin = QSpinBox(self.chroma_tab)
        self.threshold_spin.setObjectName(u"threshold_spin")
        self.threshold_spin.setGeometry(QRect(1150, 190, 62, 22))
        self.threshold_spin.setMinimum(0)
        self.threshold_spin.setMaximum(255)
        self.threshold_spin.setValue(128)
        self.min_brightness_label = QLabel(self.chroma_tab)
        self.min_brightness_label.setObjectName(u"min_brightness_label")
        self.min_brightness_label.setGeometry(QRect(730, 350, 161, 20))
        self.min_brightness_slider = QSlider(self.chroma_tab)
        self.min_brightness_slider.setObjectName(u"min_brightness_slider")
        self.min_brightness_slider.setGeometry(QRect(730, 370, 161, 22))
        self.min_brightness_slider.setMinimum(0)
        self.min_brightness_slider.setMaximum(255)
        self.min_brightness_slider.setValue(0)
        self.min_brightness_slider.setOrientation(Qt.Orientation.Horizontal)
        self.min_brightness_spin = QSpinBox(self.chroma_tab)
        self.min_brightness_spin.setObjectName(u"min_brightness_spin")
        self.min_brightness_spin.setGeometry(QRect(900, 370, 62, 22))
        self.min_brightness_spin.setMinimum(0)
        self.min_brightness_spin.setMaximum(255)
        self.min_brightness_spin.setValue(0)
        self.max_brightness_label = QLabel(self.chroma_tab)
        self.max_brightness_label.setObjectName(u"max_brightness_label")
        self.max_brightness_label.setGeometry(QRect(730, 400, 161, 20))
        self.max_brightness_slider = QSlider(self.chroma_tab)
        self.max_brightness_slider.setObjectName(u"max_brightness_slider")
        self.max_brightness_slider.setGeometry(QRect(730, 420, 161, 22))
        self.max_brightness_slider.setMinimum(0)
        self.max_brightness_slider.setMaximum(255)
        self.max_brightness_slider.setValue(255)
        self.max_brightness_slider.setOrientation(Qt.Orientation.Horizontal)
        self.max_brightness_spin = QSpinBox(self.chroma_tab)
        self.max_brightness_spin.setObjectName(u"max_brightness_spin")
        self.max_brightness_spin.setGeometry(QRect(900, 420, 62, 22))
        self.max_brightness_spin.setMinimum(0)
        self.max_brightness_spin.setMaximum(255)
        self.max_brightness_spin.setValue(255)
        self.constant_value_label = QLabel(self.chroma_tab)
        self.constant_value_label.setObjectName(u"constant_value_label")
        self.constant_value_label.setGeometry(QRect(730, 450, 161, 20))
        self.constant_value_slider = QSlider(self.chroma_tab)
        self.constant_value_slider.setObjectName(u"constant_value_slider")
        self.constant_value_slider.setGeometry(QRect(730, 470, 161, 22))
        self.constant_value_slider.setMinimum(0)
        self.constant_value_slider.setMaximum(255)
        self.constant_value_slider.setValue(0)
        self.constant_value_slider.setOrientation(Qt.Orientation.Horizontal)
        self.constant_value_spin = QSpinBox(self.chroma_tab)
        self.constant_value_spin.setObjectName(u"constant_value_spin")
        self.constant_value_spin.setGeometry(QRect(900, 470, 62, 22))
        self.constant_value_spin.setMinimum(0)
        self.constant_value_spin.setMaximum(255)
        self.constant_value_spin.setValue(0)
        self.constant_radio = QRadioButton(self.chroma_tab)
        self.constant_radio.setObjectName(u"constant_radio")
        self.constant_radio.setGeometry(QRect(730, 500, 161, 20))
        self.constant_radio.setChecked(True)
        self.original_radio = QRadioButton(self.chroma_tab)
        self.original_radio.setObjectName(u"original_radio")
        self.original_radio.setGeometry(QRect(730, 520, 161, 20))
        self.tabWidget.addTab(self.chroma_tab, "")
        self.smooth_tab = QWidget()
        self.smooth_tab.setObjectName(u"smooth_tab")
        self.smooth_frame = QFrame(self.smooth_tab)
        self.smooth_frame.setObjectName(u"smooth_frame")
        self.smooth_frame.setGeometry(QRect(80, 70, 600, 600))
        self.smooth_frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.smooth_frame.setFrameShadow(QFrame.Shadow.Raised)
        self.add_noise_button = QPushButton(self.smooth_tab)
        self.add_noise_button.setObjectName(u"add_noise_button")
        self.add_noise_button.setGeometry(QRect(730, 270, 161, 26))
        self.rectangular_button = QPushButton(self.smooth_tab)
        self.rectangular_button.setObjectName(u"rectangular_button")
        self.rectangular_button.setGeometry(QRect(730, 70, 161, 26))
        self.median_button = QPushButton(self.smooth_tab)
        self.median_button.setObjectName(u"median_button")
        self.median_button.setGeometry(QRect(730, 100, 161, 26))
        self.gaussian_button = QPushButton(self.smooth_tab)
        self.gaussian_button.setObjectName(u"gaussian_button")
        self.gaussian_button.setGeometry(QRect(730, 160, 161, 26))
        self.sigma_button = QPushButton(self.smooth_tab)
        self.sigma_button.setObjectName(u"sigma_button")
        self.sigma_button.setGeometry(QRect(730, 190, 161, 26))
        self.difference_button = QPushButton(self.smooth_tab)
        self.difference_button.setObjectName(u"difference_button")
        self.difference_button.setGeometry(QRect(730, 310, 161, 26))
        self.sigma_label = QLabel(self.smooth_tab)
        self.sigma_label.setObjectName(u"sigma_label")
        self.sigma_label.setGeometry(QRect(900, 140, 161, 20))
        self.sigma_slider = QSlider(self.smooth_tab)
        self.sigma_slider.setObjectName(u"sigma_slider")
        self.sigma_slider.setGeometry(QRect(900, 160, 161, 22))
        self.sigma_slider.setMinimum(1)
        self.sigma_slider.setMaximum(500)
        self.sigma_slider.setValue(10)
        self.sigma_slider.setOrientation(Qt.Orientation.Horizontal)
        self.sigma_spin = QDoubleSpinBox(self.smooth_tab)
        self.sigma_spin.setObjectName(u"sigma_spin")
        self.sigma_spin.setGeometry(QRect(1070, 160, 62, 22))
        self.sigma_spin.setMinimum(0.100000000000000)
        self.sigma_spin.setMaximum(50.000000000000000)
        self.sigma_spin.setValue(1.000000000000000)
        self.kernel3_radio = QRadioButton(self.smooth_tab)
        self.kernel3_radio.setObjectName(u"kernel3_radio")
        self.kernel3_radio.setGeometry(QRect(910, 90, 161, 20))
        self.kernel3_radio.setChecked(True)
        self.kernel5_radio = QRadioButton(self.smooth_tab)
        self.kernel5_radio.setObjectName(u"kernel5_radio")
        self.kernel5_radio.setGeometry(QRect(1020, 90, 161, 20))
        self.tabWidget.addTab(self.smooth_tab, "")
        self.clarity_tab = QWidget()
        self.clarity_tab.setObjectName(u"clarity_tab")
        self.clarity_frame = QFrame(self.clarity_tab)
        self.clarity_frame.setObjectName(u"clarity_frame")
        self.clarity_frame.setGeometry(QRect(80, 70, 600, 600))
        self.clarity_frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.clarity_frame.setFrameShadow(QFrame.Shadow.Raised)
        self.unsharp_button = QPushButton(self.clarity_tab)
        self.unsharp_button.setObjectName(u"unsharp_button")
        self.unsharp_button.setGeometry(QRect(730, 70, 161, 26))
        self.k_label = QLabel(self.clarity_tab)
        self.k_label.setObjectName(u"k_label")
        self.k_label.setGeometry(QRect(730, 110, 161, 20))
        self.k_slider = QSlider(self.clarity_tab)
        self.k_slider.setObjectName(u"k_slider")
        self.k_slider.setGeometry(QRect(730, 130, 161, 22))
        self.k_slider.setMinimum(1)
        self.k_slider.setMaximum(20)
        self.k_slider.setValue(3)
        self.k_slider.setOrientation(Qt.Orientation.Horizontal)
        self.k_spin = QSpinBox(self.clarity_tab)
        self.k_spin.setObjectName(u"k_spin")
        self.k_spin.setGeometry(QRect(900, 130, 62, 22))
        self.k_spin.setMinimum(1)
        self.k_spin.setMaximum(20)
        self.k_spin.setValue(3)
        self.lambda_label = QLabel(self.clarity_tab)
        self.lambda_label.setObjectName(u"lambda_label")
        self.lambda_label.setGeometry(QRect(730, 160, 161, 20))
        self.lambda_slider = QSlider(self.clarity_tab)
        self.lambda_slider.setObjectName(u"lambda_slider")
        self.lambda_slider.setGeometry(QRect(730, 180, 161, 22))
        self.lambda_slider.setMinimum(0)
        self.lambda_slider.setMaximum(50)
        self.lambda_slider.setValue(10)
        self.lambda_slider.setOrientation(Qt.Orientation.Horizontal)
        self.lambda_spin = QDoubleSpinBox(self.clarity_tab)
        self.lambda_spin.setObjectName(u"lambda_spin")
        self.lambda_spin.setGeometry(QRect(900, 180, 62, 22))
        self.lambda_spin.setMinimum(0.000000000000000)
        self.lambda_spin.setMaximum(5.000000000000000)
        self.lambda_spin.setValue(1.000000000000000)
        self.tabWidget.addTab(self.clarity_tab, "")
        self.reset_button = QPushButton(self.centralwidget)
        self.reset_button.setObjectName(u"reset_button")
        self.reset_button.setGeometry(QRect(260, 10, 161, 26))
        Imchanger.setCentralWidget(self.centralwidget)
        self.filename_label.raise_()
        self.load_button.raise_()
        self.reset_button.raise_()
        self.tabWidget.raise_()
        self.statusbar = QStatusBar(Imchanger)
        self.statusbar.setObjectName(u"statusbar")
        Imchanger.setStatusBar(self.statusbar)

        self.retranslateUi(Imchanger)

        self.tabWidget.setCurrentIndex(1)


        QMetaObject.connectSlotsByName(Imchanger)
    # setupUi

    def retranslateUi(self, Imchanger):
        Imchanger.setWindowTitle(QCoreApplication.translate("Imchanger", u"MainWindow", None))
        self.actionload_file.setText(QCoreApplication.translate("Imchanger", u"load_file", None))
        self.filename_label.setText(QCoreApplication.translate("Imchanger", u"Your file", None))
        self.load_button.setText(QCoreApplication.translate("Imchanger", u"Load File", None))
        self.label1.setText(QCoreApplication.translate("Imchanger", u"Original", None))
        self.label2.setText(QCoreApplication.translate("Imchanger", u"Cromaticity", None))
        self.label3.setText(QCoreApplication.translate("Imchanger", u"Smoothing", None))
        self.label4.setText(QCoreApplication.translate("Imchanger", u"Clarity", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.main_tab), QCoreApplication.translate("Imchanger", u"Main page", None))
        self.label.setText("")
        self.log_button.setText(QCoreApplication.translate("Imchanger", u"Logarithmic", None))
        self.power_button.setText(QCoreApplication.translate("Imchanger", u"Power Transform", None))
        self.binary_button.setText(QCoreApplication.translate("Imchanger", u"Binary", None))
        self.range_button.setText(QCoreApplication.translate("Imchanger", u"Brightness Range", None))
        self.gamma_label.setText(QCoreApplication.translate("Imchanger", u"Gamma:", None))
        self.threshold_label.setText(QCoreApplication.translate("Imchanger", u"Threshold:", None))
        self.min_brightness_label.setText(QCoreApplication.translate("Imchanger", u"Min Brightness:", None))
        self.max_brightness_label.setText(QCoreApplication.translate("Imchanger", u"Max Brightness:", None))
        self.constant_value_label.setText(QCoreApplication.translate("Imchanger", u"Constant Value:", None))
        self.constant_radio.setText(QCoreApplication.translate("Imchanger", u"Use constant value", None))
        self.original_radio.setText(QCoreApplication.translate("Imchanger", u"Keep original", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.chroma_tab), QCoreApplication.translate("Imchanger", u"\u0421hromaticity", None))
        self.add_noise_button.setText(QCoreApplication.translate("Imchanger", u"Add Noise", None))
        self.rectangular_button.setText(QCoreApplication.translate("Imchanger", u"Rectangular Filter", None))
        self.median_button.setText(QCoreApplication.translate("Imchanger", u"Median Filter", None))
        self.gaussian_button.setText(QCoreApplication.translate("Imchanger", u"Gaussian Filter", None))
        self.sigma_button.setText(QCoreApplication.translate("Imchanger", u"Sigma Filter", None))
        self.difference_button.setText(QCoreApplication.translate("Imchanger", u"Show Difference", None))
        self.sigma_label.setText(QCoreApplication.translate("Imchanger", u"Sigma:", None))
        self.kernel3_radio.setText(QCoreApplication.translate("Imchanger", u"3x3 Kernel", None))
        self.kernel5_radio.setText(QCoreApplication.translate("Imchanger", u"5x5 Kernel", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.smooth_tab), QCoreApplication.translate("Imchanger", u"Smoothing", None))
        self.unsharp_button.setText(QCoreApplication.translate("Imchanger", u"Unsharp Masking", None))
        self.k_label.setText(QCoreApplication.translate("Imchanger", u"K (kernel size):", None))
        self.lambda_label.setText(QCoreApplication.translate("Imchanger", u"Lambda (strength):", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.clarity_tab), QCoreApplication.translate("Imchanger", u"Clarity", None))
        self.reset_button.setText(QCoreApplication.translate("Imchanger", u"Reset changes", None))
    # retranslateUi

