# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'design.ui'
##
## Created by: Qt User Interface Compiler version 6.9.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QGroupBox, QLabel,
    QMainWindow, QMenuBar, QPushButton, QRadioButton,
    QSizePolicy, QSlider, QStatusBar, QWidget, QComboBox, 
    QLineEdit, QTextEdit, QCheckBox)

class Ui_Imchanger(object):
    def setupUi(self, Imchanger):
        if not Imchanger.objectName():
            Imchanger.setObjectName(u"Imchanger")
        Imchanger.resize(1704, 1100)
        self.actionload_file = QAction(Imchanger)
        self.actionload_file.setObjectName(u"actionload_file")
        icon = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.DocumentSave))
        self.actionload_file.setIcon(icon)
        self.actionload_file.setMenuRole(QAction.MenuRole.NoRole)
        self.centralwidget = QWidget(Imchanger)
        self.centralwidget.setObjectName(u"centralwidget")
        self.img_frame = QFrame(self.centralwidget)
        self.img_frame.setObjectName(u"img_frame")
        self.img_frame.setGeometry(QRect(20, 50, 512, 512))
        self.img_frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.img_frame.setFrameShadow(QFrame.Shadow.Raised)
        self.filename_label = QLabel(self.centralwidget)
        self.filename_label.setObjectName(u"filename_label")
        self.filename_label.setGeometry(QRect(190, 10, 161, 20))
        self.filename_label.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.load_button = QPushButton(self.centralwidget)
        self.load_button.setObjectName(u"load_button")
        self.load_button.setGeometry(QRect(20, 10, 161, 26))
        self.gray_frame = QFrame(self.centralwidget)
        self.gray_frame.setObjectName(u"gray_frame")
        self.gray_frame.setGeometry(QRect(1070, 20, 201, 211))
        self.gray_text = QLabel(self.centralwidget)
        self.gray_text.setObjectName(u"gray_text")
        self.gray_text.setGeometry(QRect(990, 80, 71, 91))
        self.gray_text.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.gray_text.setWordWrap(True)
        self.red_text = QLabel(self.centralwidget)
        self.red_text.setObjectName(u"red_text")
        self.red_text.setGeometry(QRect(980, 500, 66, 41))
        self.red_text.setWordWrap(True)
        self.blue_text = QLabel(self.centralwidget)
        self.blue_text.setObjectName(u"blue_text")
        self.blue_text.setGeometry(QRect(990, 300, 66, 41))
        self.blue_text.setWordWrap(True)
        self.green_text = QLabel(self.centralwidget)
        self.green_text.setObjectName(u"green_text")
        self.green_text.setGeometry(QRect(970, 710, 81, 41))
        self.green_text.setWordWrap(True)
        self.red_frame = QFrame(self.centralwidget)
        self.red_frame.setObjectName(u"red_frame")
        self.red_frame.setGeometry(QRect(1070, 440, 201, 181))
        self.blue_frame = QFrame(self.centralwidget)
        self.blue_frame.setObjectName(u"blue_frame")
        self.blue_frame.setGeometry(QRect(1070, 240, 201, 191))
        self.green_frame = QFrame(self.centralwidget)
        self.green_frame.setObjectName(u"green_frame")
        self.green_frame.setGeometry(QRect(1070, 630, 201, 201))
        self.cursor_frame = QFrame(self.centralwidget)
        self.cursor_frame.setObjectName(u"cursor_frame")
        self.cursor_frame.setGeometry(QRect(640, 70, 161, 161))
        self.cursor_frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.cursor_frame.setFrameShadow(QFrame.Shadow.Raised)
        self.gray_hist = QFrame(self.centralwidget)
        self.gray_hist.setObjectName(u"gray_hist")
        self.gray_hist.setGeometry(QRect(1290, 20, 391, 211))
        self.gray_hist.setFrameShape(QFrame.Shape.StyledPanel)
        self.gray_hist.setFrameShadow(QFrame.Shadow.Raised)
        self.blue_hist = QFrame(self.centralwidget)
        self.blue_hist.setObjectName(u"blue_hist")
        self.blue_hist.setGeometry(QRect(1290, 240, 391, 191))
        self.blue_hist.setFrameShape(QFrame.Shape.StyledPanel)
        self.blue_hist.setFrameShadow(QFrame.Shadow.Raised)
        self.red_hist = QFrame(self.centralwidget)
        self.red_hist.setObjectName(u"red_hist")
        self.red_hist.setGeometry(QRect(1290, 440, 391, 181))
        self.red_hist.setFrameShape(QFrame.Shape.StyledPanel)
        self.red_hist.setFrameShadow(QFrame.Shadow.Raised)
        self.green_hist = QFrame(self.centralwidget)
        self.green_hist.setObjectName(u"green_hist")
        self.green_hist.setGeometry(QRect(1290, 630, 391, 201))
        self.green_hist.setFrameShape(QFrame.Shape.StyledPanel)
        self.green_hist.setFrameShadow(QFrame.Shadow.Raised)
        self.coords_label = QLabel(self.centralwidget)
        self.coords_label.setObjectName(u"coords_label")
        self.coords_label.setGeometry(QRect(650, 17, 151, 51))
        self.coords_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lf_simple_button = QPushButton(self.centralwidget)
        self.lf_simple_button.setObjectName(u"lf_simple_button")
        self.lf_simple_button.setGeometry(QRect(660, 580, 131, 31))
        self.hf_simple_button = QPushButton(self.centralwidget)
        self.hf_simple_button.setObjectName(u"hf_simple_button")
        self.hf_simple_button.setGeometry(QRect(670, 680, 131, 31))
        self.c_slider = QSlider(self.centralwidget)
        self.c_slider.setObjectName(u"c_slider")
        self.c_slider.setGeometry(QRect(620, 650, 160, 16))
        self.c_slider.setTabletTracking(True)
        self.c_slider.setMinimum(1)
        self.c_slider.setMaximum(100)
        self.c_slider.setSingleStep(1)
        self.c_slider.setPageStep(0)
        self.c_slider.setValue(10)
        self.c_slider.setOrientation(Qt.Orientation.Horizontal)
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(620, 630, 21, 18))
        self.save_button = QPushButton(self.centralwidget)
        self.save_button.setObjectName(u"save_button")
        self.save_button.setGeometry(QRect(300, 10, 161, 26))
        self.reset_button = QPushButton(self.centralwidget)
        self.reset_button.setObjectName(u"reset_button")
        self.reset_button.setGeometry(QRect(630, 310, 111, 26))
        self.negative_button = QPushButton(self.centralwidget)
        self.negative_button.setObjectName(u"negative_button")
        self.negative_button.setGeometry(QRect(630, 250, 111, 26))
        self.rotate_90_button = QPushButton(self.centralwidget)
        self.rotate_90_button.setObjectName(u"rotate_90_button")
        self.rotate_90_button.setGeometry(QRect(750, 250, 111, 26))
        self.rgb_to_grb_button = QPushButton(self.centralwidget)
        self.rgb_to_grb_button.setObjectName(u"rgb_to_grb_button")
        self.rgb_to_grb_button.setGeometry(QRect(750, 280, 111, 26))
        self.reflect_by_v_button = QPushButton(self.centralwidget)
        self.reflect_by_v_button.setObjectName(u"reflect_by_v_button")
        self.reflect_by_v_button.setGeometry(QRect(630, 280, 111, 26))
        self.grb_to_rgb_button = QPushButton(self.centralwidget)
        self.grb_to_rgb_button.setObjectName(u"grb_to_rgb_button")
        self.grb_to_rgb_button.setGeometry(QRect(750, 310, 111, 26))
        self.brightness_slider = QSlider(self.centralwidget)
        self.brightness_slider.setObjectName(u"brightness_slider")
        self.brightness_slider.setGeometry(QRect(640, 370, 211, 16))
        self.brightness_slider.setTabletTracking(True)
        self.brightness_slider.setMinimum(-128)
        self.brightness_slider.setMaximum(127)
        self.brightness_slider.setSingleStep(1)
        self.brightness_slider.setPageStep(0)
        self.brightness_slider.setValue(0)
        self.brightness_slider.setOrientation(Qt.Orientation.Horizontal)
        self.contrast_slider = QSlider(self.centralwidget)
        self.contrast_slider.setObjectName(u"contrast_slider")
        self.contrast_slider.setGeometry(QRect(640, 410, 211, 16))
        self.contrast_slider.setTabletTracking(True)
        self.contrast_slider.setMinimum(1)
        self.contrast_slider.setMaximum(100)
        self.contrast_slider.setSingleStep(1)
        self.contrast_slider.setPageStep(0)
        self.contrast_slider.setValue(10)
        self.contrast_slider.setOrientation(Qt.Orientation.Horizontal)
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(640, 390, 101, 18))
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(640, 350, 101, 18))
        self.brightness_label = QLabel(self.centralwidget)
        self.brightness_label.setObjectName(u"brightness_label")
        self.brightness_label.setGeometry(QRect(860, 370, 131, 18))
        self.contrast_label = QLabel(self.centralwidget)
        self.contrast_label.setObjectName(u"contrast_label")
        self.contrast_label.setGeometry(QRect(860, 410, 141, 18))
        self.stats_label = QLabel(self.centralwidget)
        self.stats_label.setObjectName(u"stats_label")
        self.stats_label.setGeometry(QRect(30, 580, 171, 221))
        self.stats_label.setFrameShape(QFrame.Shape.Box)
        self.stats_label.setFrameShadow(QFrame.Shadow.Raised)
        self.stats_label.setLineWidth(2)
        self.groupBox = QGroupBox(self.centralwidget)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(620, 460, 241, 111))
        self.average_blur_rbutton = QRadioButton(self.groupBox)
        self.average_blur_rbutton.setObjectName(u"average_blur_rbutton")
        self.average_blur_rbutton.setGeometry(QRect(10, 30, 110, 23))
        self.average_blur_rbutton.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.gauss_filter_rbutton = QRadioButton(self.groupBox)
        self.gauss_filter_rbutton.setObjectName(u"gauss_filter_rbutton")
        self.gauss_filter_rbutton.setGeometry(QRect(10, 80, 110, 23))
        self.c_label = QLabel(self.centralwidget)
        self.c_label.setObjectName(u"c_label")
        self.c_label.setGeometry(QRect(800, 650, 131, 18))
        
        # Дополнительные UI элементы для новых функций
        self.convolution_group = QGroupBox(self.centralwidget)
        self.convolution_group.setObjectName(u"convolution_group")
        self.convolution_group.setGeometry(QRect(20, 820, 300, 200))
        
        self.kernel_combo = QComboBox(self.convolution_group)
        self.kernel_combo.setObjectName(u"kernel_combo")
        self.kernel_combo.setGeometry(QRect(10, 20, 120, 22))
        
        self.kernel_size_edit = QLineEdit(self.convolution_group)
        self.kernel_size_edit.setObjectName(u"kernel_size_edit")
        self.kernel_size_edit.setGeometry(QRect(140, 20, 40, 22))
        
        self.kernel_text_edit = QTextEdit(self.convolution_group)
        self.kernel_text_edit.setObjectName(u"kernel_text_edit")
        self.kernel_text_edit.setGeometry(QRect(10, 50, 280, 60))
        
        self.normalize_checkbox = QCheckBox(self.convolution_group)
        self.normalize_checkbox.setObjectName(u"normalize_checkbox")
        self.normalize_checkbox.setGeometry(QRect(10, 120, 100, 20))
        
        self.add_128_checkbox = QCheckBox(self.convolution_group)
        self.add_128_checkbox.setObjectName(u"add_128_checkbox")
        self.add_128_checkbox.setGeometry(QRect(120, 120, 100, 20))
        
        self.apply_convolution_button = QPushButton(self.convolution_group)
        self.apply_convolution_button.setObjectName(u"apply_convolution_button")
        self.apply_convolution_button.setGeometry(QRect(10, 150, 120, 30))
        
        self.corner_group = QGroupBox(self.centralwidget)
        self.corner_group.setObjectName(u"corner_group")
        self.corner_group.setGeometry(QRect(330, 820, 250, 150))
        
        self.harris_button = QPushButton(self.corner_group)
        self.harris_button.setObjectName(u"harris_button")
        self.harris_button.setGeometry(QRect(10, 30, 80, 30))
        
        self.shi_tomasi_button = QPushButton(self.corner_group)
        self.shi_tomasi_button.setObjectName(u"shi_tomasi_button")
        self.shi_tomasi_button.setGeometry(QRect(130, 30, 80, 30))
        
        self.corner_threshold_slider = QSlider(self.corner_group)
        self.corner_threshold_slider.setObjectName(u"corner_threshold_slider")
        self.corner_threshold_slider.setGeometry(QRect(90, 70, 100, 16))
        self.corner_threshold_slider.setMinimum(1)
        self.corner_threshold_slider.setMaximum(255)
        self.corner_threshold_slider.setValue(10)
        self.corner_threshold_slider.setOrientation(Qt.Orientation.Horizontal)
        
        self.corner_threshold_label = QLabel(self.corner_group)
        self.corner_threshold_label.setObjectName(u"corner_threshold_label")
        self.corner_threshold_label.setGeometry(QRect(10, 70, 80, 16))
        
        self.edge_group = QGroupBox(self.centralwidget)
        self.edge_group.setObjectName(u"edge_group")
        self.edge_group.setGeometry(QRect(740, 820, 250, 150))
        
        self.sobel_button = QPushButton(self.edge_group)
        self.sobel_button.setObjectName(u"sobel_button")
        self.sobel_button.setGeometry(QRect(20, 30, 80, 30))
        
        self.canny_button = QPushButton(self.edge_group)
        self.canny_button.setObjectName(u"canny_button")
        self.canny_button.setGeometry(QRect(140, 30, 80, 30))
        
        self.canny_low_slider = QSlider(self.edge_group)
        self.canny_low_slider.setObjectName(u"canny_low_slider")
        self.canny_low_slider.setGeometry(QRect(50, 70, 150, 16))
        self.canny_low_slider.setMinimum(10)
        self.canny_low_slider.setMaximum(200)
        self.canny_low_slider.setValue(50)
        self.canny_low_slider.setOrientation(Qt.Orientation.Horizontal)
        
        self.canny_high_slider = QSlider(self.edge_group)
        self.canny_high_slider.setObjectName(u"canny_high_slider")
        self.canny_high_slider.setGeometry(QRect(50, 100, 150, 16))
        self.canny_high_slider.setMinimum(50)
        self.canny_high_slider.setMaximum(300)
        self.canny_high_slider.setValue(150)
        self.canny_high_slider.setOrientation(Qt.Orientation.Horizontal)
        
        self.canny_low_label = QLabel(self.edge_group)
        self.canny_low_label.setObjectName(u"canny_low_label")
        self.canny_low_label.setGeometry(QRect(10, 70, 40, 16))
        
        self.canny_high_label = QLabel(self.edge_group)
        self.canny_high_label.setObjectName(u"canny_high_label")
        self.canny_high_label.setGeometry(QRect(10, 100, 40, 16))
        
        Imchanger.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(Imchanger)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1704, 23))
        Imchanger.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(Imchanger)
        self.statusbar.setObjectName(u"statusbar")
        Imchanger.setStatusBar(self.statusbar)

        self.retranslateUi(Imchanger)

        QMetaObject.connectSlotsByName(Imchanger)
    # setupUi

    def retranslateUi(self, Imchanger):
        Imchanger.setWindowTitle(QCoreApplication.translate("Imchanger", u"MainWindow", None))
        self.actionload_file.setText(QCoreApplication.translate("Imchanger", u"load_file", None))
        self.filename_label.setText(QCoreApplication.translate("Imchanger", u"Your file", None))
        self.load_button.setText(QCoreApplication.translate("Imchanger", u"Load File", None))
        self.gray_text.setText(QCoreApplication.translate("Imchanger", u"W/B preview", None))
        self.red_text.setText(QCoreApplication.translate("Imchanger", u"Only red preview", None))
        self.blue_text.setText(QCoreApplication.translate("Imchanger", u"Only blue preview", None))
        self.green_text.setText(QCoreApplication.translate("Imchanger", u"Only green preview", None))
        self.coords_label.setText(QCoreApplication.translate("Imchanger", u"Coords", None))
        self.lf_simple_button.setText(QCoreApplication.translate("Imchanger", u"Get LF Image", None))
        self.hf_simple_button.setText(QCoreApplication.translate("Imchanger", u"Get HF Image", None))
        self.label.setText(QCoreApplication.translate("Imchanger", u"c", None))
        self.save_button.setText(QCoreApplication.translate("Imchanger", u"Save File", None))
        self.reset_button.setText(QCoreApplication.translate("Imchanger", u"Reset all", None))
        self.negative_button.setText(QCoreApplication.translate("Imchanger", u"Negative", None))
        self.rotate_90_button.setText(QCoreApplication.translate("Imchanger", u"Rotate 90 d.", None))
        self.rgb_to_grb_button.setText(QCoreApplication.translate("Imchanger", u"RGB->GRB", None))
        self.reflect_by_v_button.setText(QCoreApplication.translate("Imchanger", u"Reflect", None))
        self.grb_to_rgb_button.setText(QCoreApplication.translate("Imchanger", u"GRB->RGB", None))
        self.label_2.setText(QCoreApplication.translate("Imchanger", u"Contrast", None))
        self.label_3.setText(QCoreApplication.translate("Imchanger", u"Brightness", None))
        self.brightness_label.setText("")
        self.contrast_label.setText("")
        self.stats_label.setText(QCoreApplication.translate("Imchanger", u"Stats", None))
        self.groupBox.setTitle(QCoreApplication.translate("Imchanger", u"Simple LF ilter", None))
        self.average_blur_rbutton.setText(QCoreApplication.translate("Imchanger", u"Average Blur", None))
        self.gauss_filter_rbutton.setText(QCoreApplication.translate("Imchanger", u"Gauss Filter", None))
        self.c_label.setText(QCoreApplication.translate("Imchanger", u"1.0", None))
        
        # Тексты для новых элементов
        self.convolution_group.setTitle(QCoreApplication.translate("Imchanger", u"Свёртка с матрицей", None))
        self.kernel_size_edit.setText(QCoreApplication.translate("Imchanger", u"3", None))
        self.kernel_text_edit.setPlainText(QCoreApplication.translate("Imchanger", u"1 1 1\n1 1 1\n1 1 1", None))
        self.normalize_checkbox.setText(QCoreApplication.translate("Imchanger", u"Нормализация", None))
        self.add_128_checkbox.setText(QCoreApplication.translate("Imchanger", u"+128", None))
        self.apply_convolution_button.setText(QCoreApplication.translate("Imchanger", u"Применить свёртку", None))
        
        self.corner_group.setTitle(QCoreApplication.translate("Imchanger", u"Детекция углов", None))
        self.harris_button.setText(QCoreApplication.translate("Imchanger", u"Харрис", None))
        self.shi_tomasi_button.setText(QCoreApplication.translate("Imchanger", u"Shi-Tomasi", None))
        self.corner_threshold_label.setText(QCoreApplication.translate("Imchanger", u"Порог:", None))
        
        self.edge_group.setTitle(QCoreApplication.translate("Imchanger", u"Детекция границ", None))
        self.sobel_button.setText(QCoreApplication.translate("Imchanger", u"Собель", None))
        self.canny_button.setText(QCoreApplication.translate("Imchanger", u"Канни", None))
        self.canny_low_label.setText(QCoreApplication.translate("Imchanger", u"Низ:", None))
        self.canny_high_label.setText(QCoreApplication.translate("Imchanger", u"Выс:", None))
    # retranslateUi
    
    def setup_additional_controls(self):
        """Инициализирует дополнительные элементы управления"""
        # Импортируем функцию здесь, чтобы избежать циклических импортов
        from helpers import get_standard_kernels
        
        # Заполняем ComboBox стандартными ядрами
        standard_kernels = get_standard_kernels()
        self.kernel_combo.addItems(standard_kernels.keys())
        
        # Устанавливаем начальные значения
        self.normalize_checkbox.setChecked(True)
        self.kernel_size_edit.setText("3")
        self.kernel_text_edit.setPlainText("1 1 1\n1 1 1\n1 1 1")

